bookssummaries/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('summary/', include('summary.urls', namespace='summary')),
]

# serving media files only during developement
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

summary/urls.py
from django.urls import include, path
from . import views

app_name = 'summary'

urlpatterns = [
    # summarys urls 
    path('', views.SummaryList.as_view(), name='summary_list'),
    path('<int:tag_id>/', views.SummaryList.as_view(), name='summary_list'),
    path('add/', views.SummaryCreate.as_view(), name='summary_add'),
    path('<int:pk>/detail/', views.SummaryDetail.as_view(), name='summary_detail'),
    path('<int:pk>/download', views.SummaryDownload.as_view(), name='summary_download'),
    path('<int:pk>/update/', views.SummaryUpdate.as_view(), name='summary_update'),
    path('<int:pk>/delete/', views.SummaryDelete.as_view(), name='summary_delete'),
]

summary/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager


class Summary(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField(blank=True)
    tags = TaggableManager()
    created = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey('auth.User', related_name='summaries', on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('summary:summary_detail', kwargs={'pk': self.pk})
                     
    class Meta:
        ordering = ['-created']

summary/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template.loader import render_to_string
from django.core.files.storage import FileSystemStorage
from django.template.loader import render_to_string
# messages framework
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
# class-based generic views
from django.views.generic import ListView, DetailView, View
from django.views.generic.edit import CreateView, DeleteView, UpdateView
# third party imports
from taggit.models import Tag
from weasyprint import HTML
# import models
from django.contrib.auth.models import User
from .models import Summary



class SummaryList(ListView): 
    model = Summary
    template_name = 'summary/summary/summary_list.html'
    context_object_name = 'summary_list'
    paginate_by = 5

    def get_queryset(self):
        if 'tag_id' in self.kwargs:
            tag = get_object_or_404(Tag, pk=self.kwargs['tag_id']) 
            return Summary.objects.filter(tags__in=[tag]) # filter posts (tags__in ???)
        else:
            return Summary.objects.all()


class SummaryDetail(DetailView):
    model = Summary
    template_name = 'summary/summary/summary_detail.html'
    context_object_name = 'summary'


class SummaryCreate(SuccessMessageMixin, LoginRequiredMixin, CreateView): 
    model = Summary
    template_name = 'summary/summary/summary_form_create.html' 
    fields = ['title', 'body', 'tags']
    success_message = "Summary was created successfully"

    def form_valid(self, form):
        form.instance.owner = self.request.user # add summary owner 
        return super().form_valid(form)


class SummaryUpdate(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Summary
    template_name = 'summary/summary/summary_form_update.html' 
    fields = ['title', 'body', 'tags']
    success_message = "Summary was updated successfully"

    def form_valid(self, form):
        # user should be the summary owner 
        if form.instance.owner == self.request.user:
            return super().form_valid(form)
        else:
            return HttpResponse('You are not summary owner')


class SummaryDelete(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = Summary
    template_name = 'summary/summary/summary_confirm_delete.html' 
    success_message = "Summary was deleted successfully"
    success_url = reverse_lazy('summary:summary_list')

    def form_valid(self, form):
        # user should be the summary owner 
        if form.instance.publisher == self.request.user:
            return super().form_valid(form)
        else:
            return HttpResponse('You are not summary owner')

    def delete(self, request, *args, **kwargs):
        # inform user that "Summary was deleted successfully"
        messages.info(request, self.success_message)
        return super().delete(request, *args, **kwargs)


# download the file with weasyprint
class SummaryDownload(View):
    def get(self, request, *args, **kwargs):
        summary = get_object_or_404(Summary, pk=kwargs['pk'])
        context = {'summary': summary}
        html_string = render_to_string('summary/summary/summary_detail.html', context)

        html = HTML(string=html_string)
        html.write_pdf(target='/tmp/mypdf.pdf');

        fs = FileSystemStorage('/tmp')
        with fs.open('mypdf.pdf') as pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            response['Content-Disposition'] = 'inline; filename="mypdf.pdf"'
            return response

summary/templates/summary/summary/pagination.html
<br>
<div>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">Previous</span>
                </li>
            {% endif %}
            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="page-item active">
                        <span class="page-link">
                            {{ i }}
                            <span class="sr-only">(current)</span>
                        </span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">Next</span>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>

summary/templates/summary/summary/summary_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Delete" class='btn btn-danger'>
</form>


{% endblock %}

summary/templates/summary/summary/summary_detail.html
{% extends 'base.html' %}
{% load summary_filters %}

{% block content %}

<!-- Display summary.title and summary.owner.username -->
<h2>{{ summary.title }} By {{ summary.owner.username }} </h2>

<!-- Display summary body -->
<p> {{ summary.body|markdown_format }} </p> 

<!-- Display 'Edit' and 'Delete' buttons -->
{% if user.is_authenticated and summary.owner == request.user %}
<p>
<a href="{% url 'summary:summary_update' summary.pk %}" class="btn btn-primary"> Update </a> 
<a href="{% url 'summary:summary_delete' summary.pk %}" class="btn btn-danger"> Delete </a>
</p>
<hr />
{% endif %}

{% endblock %}

summary/templates/summary/summary/summary_form_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

 
<h3>Create summary</h3>

<form action="{% url 'summary:summary_add' %}" method="post" novalidate enctype="multipart/form-data" class="uniForm">
    {{ form|crispy }}
    {% csrf_token %}
    <p><input type="submit" value="Create" class='btn btn-primary'></p>
</form>



{% endblock %}

summary/templates/summary/summary/summary_form_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h3>Update summary</h3>

<form action="{% url 'summary:summary_update' summary.id %}" method="post" novalidate enctype="multipart/form-data" class="uniForm">
    {{ form|crispy }}
    {% csrf_token %}
    <p><input type="submit" value="Update" class='btn btn-primary'></p>
</form>

{% endblock %}

summary/templates/summary/summary/summary_list.html
{% extends 'base.html' %}
{% load summary_filters %}

{% block content %}

<!-- Inclusion tag that display all tags - 'blog/post/tags_list.html' -->
{% tags_list %}

<!-- Display list of all summaries -->
{% for summary in summary_list %}
<div class="card bg-light mb-3" style="max-width: 100%;">
  <div class="card-header">{{ summary.title }}</div>
  <div class="card-body">
    <!-- Link to display summarys for specific user -->
    <h4 class="card-title">Created By {{ summary.owner.username }} </h4>
    <p class="card-text"> {{ summary.body|markdown_format|truncatewords_html:30 }} </p>
    <a href="{{ summary.get_absolute_url }}">Detail</a>
    <a href="{% url 'summary:summary_download' pk=summary.pk %}" target="_blank" >Download</a>
  </div>
</div>
{% empty %}
<p>No summary yet</p>
{% endfor %}


<!-- Display pagination only if page_obj have some value -->
{% if page_obj %}
{% include "summary/summary/pagination.html" with page=page_obj %}
{% endif %}


{% endblock %}

summary/templates/summary/summary/tags_list.html
<!-- Display all tags -->
<div>
{% if tags_list %}
    <p class='tags'>Categories : 
        {% for tag in tags_list %}
            <a href="{% url 'summary:summary_list' tag_id=tag.id %}" class="btn btn-outline-secondary btn-sm my-2">{{ tag.name }}</a>
        {% endfor %}
    </p>
{% endif %}
</div>

<!-- Some styles to make those links in the middle -->
<style>
    p.tags{
        text-align: center;
    }
</style>